---
# Elasticsearch Configuration
cluster.name: test123
node.name: node-0
network.host: 0.0.0.0
discovery.type: single-node
#discovery.seed_hosts: ["host1", "host2"]
#cluster.initial_master_nodes: ["node-1", "node-2"]
