
---
- name: Install and Configure Elasticsearch with Docker
  hosts: localhost
  #become: true
  #become_user: lehar
  #become_method: sudo
  #ansible_become_password: "lehar"
  #password: "lehar"
  gather_facts: false
  #roles_path: /home/lehar/jeanshell/ansible/roles
  roles:
    - elasticsearch
