---

- name: Create Docker network
  docker_network:
    name: my-network

- name: Ensure config directory is present
  file:
    path: "/opt/logstash"
    state: directory
    owner: 1000
    group: 1000
    mode: "0755"

- name: Copy Logstash configuration file
  template:
    src: logstash.conf
    dest: "/opt/logstash/logstash.conf"
    owner: 1000
    group: 1000
    mode: "0755"


- name: Copy Logstash yml configuration file
  template:
    src: logstash.yml
    dest: "/opt/logstash/logstash.yml"
    owner: 1000
    group: 1000
    mode: "0755"

- name: Pull Logstash Docker image
  docker_image:
    name: docker.elastic.co/logstash/logstash:{{ logstash_version }}
    source: pull

- name: Run Logstash container
  docker_container:
    name: logstash
    image: docker.elastic.co/logstash/logstash:{{ logstash_version }}
    state: started
    restart_policy: always
    ports:

#      - "5045:5044"
      - "9600:9600"
    volumes:
      - "/opt/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
      - "/opt/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml"   
     # - "/var/log:/var/log:z"
    networks:
      -  name: my-network    
    
